/* ============================================================
   Canonical ingredient layer.
   Maps source menu strings onto reviewed ingredient identities,
   each with a profile. Match order matters:
   composed items (glazes, yogurts, milks) before plain fruits.

   band: 'everyday'  flavor, texture, base, sweetness, looks
         'functional' added for a wellness reason, not flavor
   ============================================================ */

(function () {
  // Browse by ingredient or preparation. Keep distinct formulas in specialty blends.
  const CATS = {
    fruit: 'Fruits & berries',
    veg: 'Vegetables & herbs',
    liquid: 'Milks, waters & juices',
    cultured: 'Cultured ingredients',
    brew: 'Coffee, tea & prepared drinks',
    sweet: 'Sweeteners, spices & seasonings',
    fat: 'Nuts, seeds, oils & grains',
    super: 'Powders, mushrooms & extracts',
    supplement: 'Proteins & supplements',
    topping: 'Toppings & desserts',
    specialty: 'Specialty blends',
  };

  // Each entry: id, name, cat, band, icon, re (first match wins, in array order), blurb
  const CANON = [

    /* ---- distinct preparations before their component ingredients ---- */
    { id: 'hydration-drink', name: 'Hydration drink', cat: 'brew', band: 'functional', icon: 'bottle', re: /^(?!.*(?:powder|drink mix)).*(?:\bbarcode\b|\b(?:hydration|sports|electrolyte) drink\b)/,
      blurb: 'A prepared drink with added electrolytes. The archive includes BARCODE Lemon Lime. Bottled drinks stay separate from electrolyte powders and drops.' },
    { id: 'cola', name: 'Cola', cat: 'brew', band: 'functional', icon: 'bottle', re: /\bcola\b/,
      blurb: 'A prepared cola drink used as a smoothie ingredient. The archive lists GT\'s ALIVE Cola, with the product name preserved below.' },
    { id: 'probiotic-drink', name: 'Probiotic drink', cat: 'cultured', band: 'functional', icon: 'shot', re: /\bbio-?k\b|\bprobiotic (?:drink|shot)\b/,
      blurb: 'A cultured drink containing probiotics. The archive includes Bio-K Blueberry. It stays separate from probiotics listed as a supplement.' },
    { id: 'plant-creamer', name: 'Plant-based creamer', cat: 'brew', band: 'functional', icon: 'jar', re: /copina.*collagen boost|\bplant[- ]based creamer\b/,
      blurb: 'A plant-based creamer used for richness. The archive lists Copina Vanilla Collagen Boost, a powder with added botanicals. Despite its product name, that formula contains no collagen peptides.' },
    { id: 'biosil', name: 'BioSil', cat: 'specialty', band: 'functional', icon: 'bottle', re: /\bbiosil\b/,
      blurb: 'A named product listed as Biosil collagen. The source wording is preserved without treating the product name as proof of its contents.' },
    { id: 'fish-oil', name: 'Fish oil', cat: 'fat', band: 'functional', icon: 'oil', re: /nordic naturals ultimate omega|\bfish oil\b/,
      blurb: 'An oil derived from fish. The archive lists Nordic Naturals Ultimate Omega. Plant oil blends and oils with an unspecified source remain separate.' },
    { id: 'ion-gut-support', name: 'ION Gut Support', cat: 'specialty', band: 'functional', icon: 'bottle', re: /ion gut support/,
      blurb: 'A named bottled product listed in the archive. It stays separate from generic mineral entries.' },
    { id: 'four-sigmatic-gut-health', name: 'Four Sigmatic Gut Health', cat: 'specialty', band: 'functional', icon: 'jar', re: /four sigmatic gut health/,
      blurb: 'A named blend listed as Four Sigmatic Gut Health Blend. It stays separate from individual mushrooms.' },
    { id: 'sea-moss-drink', name: 'Sea moss drink', cat: 'brew', band: 'functional', icon: 'can', re: /copina.*sea moss.*refresher|sea moss (?:drink|refresher)/,
      blurb: 'A prepared drink made with sea moss. The archive lists Copina Citrus Blossom Sea Moss Refresher, separate from sea moss used on its own.' },
    { id: 'latte-mix', name: 'Latte mix', cat: 'brew', band: 'everyday', icon: 'saffronLatte', re: /(?:pumpkin spice|saffron) latte|\blatte (?:mix|powder|blend)\b/,
      blurb: 'Prepared powders for making lattes. The archive includes Blume Pumpkin Spice and The Fullest Saffron Latte. Each flavor and product stays named in the recipe. These mixes are separate from plain spices and brewed tea or coffee.' },

    /* ---- cultured & composed first, so flavors don't mis-match ---- */
    { id: 'immunity-shot', name: 'Alo Immunity Rescue', cat: 'specialty', band: 'functional', icon: 'shot', re: /alo.*immunity rescue/,
      blurb: 'A named Alo product listed as an immunity rescue drizzle. Kept as a product rather than inferred individual ingredients.' },
    { id: 'probiotics', name: 'Probiotics', cat: 'supplement', band: 'functional', icon: 'probiotic', re: /probiotic/,
      blurb: 'Probiotics listed as a supplement. Prepared probiotic drinks have a separate profile under Cultured ingredients.' },
    { id: 'water-kefir', name: 'Water kefir', cat: 'cultured', band: 'functional', icon: 'waterKefir', re: /agua de kefir|water kefir/,
      blurb: 'A fermented water drink with a light tartness. The archive version is flavored with dragon fruit and strawberry.' },
    { id: 'coconut-kefir', name: 'Coconut kefir', cat: 'cultured', band: 'functional', icon: 'coconutKefir', re: /coconut kefir/,
      blurb: 'A fermented coconut drink with a tart flavor and a creamy plant base.' },
    { id: 'dairy-kefir', name: 'Dairy kefir', cat: 'cultured', band: 'functional', icon: 'dairyKefir', re: /lifeway.*kefir|raw farm kefir|dairy kefir/,
      blurb: 'A fermented cow\'s milk drink with a tart flavor and a pourable texture.' },
    { id: 'kefir', name: 'Kefir', cat: 'cultured', band: 'functional', icon: 'kefir', re: /kefir/,
      blurb: 'A fermented drink with a tart flavor. This generic entry is reserved for source wording that does not identify the base.' },
    { id: 'coconut-yogurt', name: 'Coconut yogurt', cat: 'cultured', band: 'functional', icon: 'yogurt', re: /cocoyo|cocojune|coconut cult|coconut yogurt|harmless harvest vanilla flavored dairy-free cup yogurt alternative/,
      blurb: 'A cultured coconut base with a thick, tangy texture. The archive includes Cocoyo, Cocojune, Coconut Cult and Harmless Harvest cup yogurt. Product names and flavors share this profile.' },
    { id: 'yogurt', name: 'Yogurt', cat: 'cultured', band: 'everyday', icon: 'genericYogurt', re: /yogurt/,
      blurb: 'A cultured, creamy ingredient used to add body and tang. Some archive labels do not identify the dairy or plant base, so those variants stay grouped under the source wording.' },
    { id: 'ice-cream', name: 'Ice cream', cat: 'topping', band: 'treats', icon: 'icecream', re: /ice cream/,
      blurb: 'Actual ice cream blended in, the shortest path from smoothie to milkshake. Alec\'s regenerative organic honey blueberry lavender pints starred in their 2023 A2 dairy shake.' },
    { id: 'dairy-whip', name: 'Dairy whipped cream', cat: 'topping', band: 'treats', icon: 'dairyWhip', re: /grass-?fed whipped cream|grassfed whipped cream|dairy cream top|^dairy whipped cream$/,
      blurb: 'Cow\'s milk cream whipped into a light topping. These archive variants explicitly identify a dairy or grass fed cream base.' },
    { id: 'whipped-cream', name: 'Whipped cream', cat: 'topping', band: 'treats', icon: 'whippedCream', re: /vegan cream top|vegan whipped cream|pitaya whipped cream|blue spirulina whipped cream|^(?!.*coconut)(?!.*grass-?fed)whipped cream$/,
      blurb: 'A light whipped topping spooned over the finished drink. The archive includes vegan and naturally colored versions, but the source wording does not always identify the base.' },
    { id: 'dairy-cream', name: 'Dairy cream', cat: 'liquid', band: 'everyday', icon: 'dairyCream', re: /^dairy cream$/,
      blurb: 'Cream from cow\'s milk, used to add richness and body. The archive lists it separately from milk and whipped toppings.' },
    { id: 'condensed-milk', name: 'Condensed milk', cat: 'liquid', band: 'treats', icon: 'condensedMilk', re: /condensed milk/,
      blurb: 'Milk concentrated into a thick, sweet liquid. It adds both dairy richness and sweetness to a blend.' },
    { id: 'dairy-milk', name: 'Dairy milk', cat: 'liquid', band: 'everyday', icon: 'cartonDairy', re: /whole milk|a2(?:\/a2)? milk|raw milk|^dairy milk$/,
      blurb: 'Cow\'s milk used as a smoothie base. Archive labels identify whole, raw, and A2 versions separately from cream and condensed milk.' },
    { id: 'milk', name: 'Milk', cat: 'liquid', band: 'everyday', icon: 'carton', re: /milk of choice|choice of milk|^milk$/,
      blurb: 'A plain milk base with the type left open, dairy or one of the house nut and coconut milks depending on the drink. Some tonic bar menus just list it as milk of choice.' },
    { id: 'glaze', name: 'Fruit glaze', cat: 'topping', band: 'treats', icon: 'glaze', re: /glaze/,
      blurb: 'A syrupy fruit swirl painted up the inside of the cup before pouring, so it streaks down the side. It is mostly fruit and sweetener, there for the look and a sharper hit of flavor. The strawberry version on Hailey Bieber\'s smoothie made it an Erewhon signature.' },
    { id: 'compote', name: 'Fruit compote', cat: 'topping', band: 'treats', icon: 'compote', re: /compote|(?<!chocolate )sauce/,
      blurb: 'Whole fruit cooked down with a little sweetener until thick enough to spoon, then layered into the cup. Cooking concentrates the flavor and softens the fruit. Seasonal blends have used raspberry goji and blackberry blueberry versions.' },
    { id: 'fig-jam', name: 'Fig jam', cat: 'topping', band: 'everyday', icon: 'figJam', re: /fig jam/,
      blurb: 'Figs cooked into a thick, spreadable fruit preserve. The housemade version adds concentrated fig sweetness and a jammy texture.' },
    { id: 'caramel', name: 'Superfood caramel', cat: 'topping', band: 'treats', icon: 'caramel', re: /caramel/,
      blurb: 'A caramel built from dates and maple instead of cooked sugar, so the sweetness comes from fruit. It still pulls and coats like the real thing. Erewhon folds in Dandy Blend and he shou wu and made its version for Emma Chamberlain\'s cold brew smoothie.' },
    { id: 'ganache', name: 'Chocolate ganache', cat: 'topping', band: 'treats', icon: 'cacao', re: /ganache/,
      blurb: 'A soft layer of chocolate and cream, here to push a smoothie toward dessert. It is rich, sweet and purely about flavor. Erewhon\'s in house Scratch bakery makes the version used in the dessert styled blends.' },
    { id: 'crust', name: 'Pie crust & graham', cat: 'topping', band: 'treats', icon: 'crust', re: /crust|graham/,
      blurb: 'Crumbled pie crust or graham cracker, blended in for the toasted, buttery note of a baked good. It is mostly texture and flavor. The crumbs come from Erewhon\'s Scratch bakery, used in the OG Goth and the holiday smoothies.' },
    { id: 'cookie', name: 'Cookie crumble', cat: 'topping', band: 'treats', icon: 'granola', re: /sweet thins|brownie|cookie/,
      blurb: 'Crushed chocolate cookies for crunch and a brownie like flavor. Erewhon uses its own Sweet Thins, the crumble in Emma Chamberlain\'s cold brew cookie smoothie.' },
    { id: 'granola', name: 'Granola', cat: 'topping', band: 'everyday', icon: 'granola', re: /granola/,
      blurb: 'A baked mixture of grains, nuts, or seeds used for crunch. Archive variants include walnut, ancient grain, and vegan granolas.' },
    { id: 'muffin-crumbles', name: 'Blueberry muffin crumbles', cat: 'topping', band: 'treats', icon: 'muffinCrumble', re: /blueberry muffin crumble/,
      blurb: 'Crumbled pieces of blueberry muffin used as a sweet topping. The source describes a baked item rather than whole blueberries.' },
    { id: 'sprinkles', name: 'Sprinkles', cat: 'topping', band: 'treats', icon: 'sprinkles', re: /sprinkle/,
      blurb: 'Sugar sprinkles for color and a little crunch on top. Erewhon used Good Dee\'s sugar free version once, on the Barbie birthday smoothie.' },
    { id: 'coconut-soft-serve', name: 'Coconut soft serve', cat: 'topping', band: 'treats', icon: 'coconutSoftServe', re: /coconut (?:creme )?soft serve/,
      blurb: 'Soft serve blended in to push a smoothie toward a milkshake, thicker and colder. Erewhon\'s is dairy free, made from coconut.' },
    { id: 'soft-serve', name: 'Soft serve', cat: 'topping', band: 'treats', icon: 'softserve', re: /soft serve/,
      blurb: 'A frozen, aerated dessert used for a thicker, colder blend. The generic archive label does not identify its base.' },
    { id: 'coconut-cream', name: 'Coconut cream', cat: 'liquid', band: 'everyday', icon: 'coconutcream', re: /coconut cream/,
      blurb: 'The thick cream skimmed off the top of coconut milk, high in fat and very rich. It is the main reason Erewhon smoothies feel as thick as they do, and it turns up in more than a third of the archive. The brand is usually Zuma Valley.' },
    { id: 'coconut-whip', name: 'Coconut whip', cat: 'topping', band: 'treats', icon: 'coconutWhip', re: /coconut whip(?:ped cream)?/,
      blurb: 'Coconut cream whipped with air until it holds soft peaks, spooned on top. It is the dairy free stand in for whipped cream, standard on the dessert styled collabs.' },

    /* ---- milks, waters, brews ---- */
    { id: 'almond-milk', name: 'Almond milk', cat: 'liquid', band: 'everyday', icon: 'cartonAlmond', re: /almond ?milk|almondmilk/,
      blurb: 'The default base across the menu, a light nut milk with a clean, faintly sweet flavor and not many calories. Most cartons are fortified with calcium and vitamin E. Erewhon usually pours MALK, whose version is just almonds, water and salt, or its own raw house blend.' },
    { id: 'oat-milk', name: 'Oat milk', cat: 'liquid', band: 'everyday', icon: 'cartonOat', re: /oat ?milk|oatmilk|koatji/,
      blurb: 'A creamier, naturally sweet plant milk pressed from oats, with a little soluble fiber the nut milks lack. It blends smooth and froths well, which is why it carries so many recent collabs. Erewhon uses MALK oat milk, including in the Laufey and Barbie smoothies.' },
    { id: 'coconut-milk', name: 'Coconut milk', cat: 'liquid', band: 'everyday', icon: 'cartonCoconut', re: /coconut milk|coconut malk/,
      blurb: 'Blended coconut meat and water, richer and higher in fat than the nut milks. It is the backbone of the tropical blends and adds body on its own. Erewhon uses MALK or Vita Coco.' },
    { id: 'eggnog', name: 'Plant based eggnog', cat: 'brew', band: 'treats', icon: 'cartonEggnog', re: /eggnog|\bnog\b/,
      blurb: 'A sweet, spiced custard drink, here in a dairy free plant version. It is rich and seasonal, a base for the winter specials.' },
    { id: 'coconut-water', name: 'Coconut water', cat: 'liquid', band: 'everyday', icon: 'coconutWater', re: /coconut water/,
      blurb: 'The clear liquid from inside a young coconut, lighter than any milk and naturally high in potassium. It thins a blend without dulling the flavor. Erewhon lists Vita Coco Farmers, Harmless Harvest and Real Coco on its cards.' },
    { id: 'hydrogen-water', name: 'Hydrogen water', cat: 'liquid', band: 'functional', icon: 'waterdrop', re: /hydrogen/,
      blurb: 'Plain water with extra hydrogen gas dissolved in, sold on the idea that the gas acts as an antioxidant. The research is thin and the gas escapes within minutes of opening the bottle. Gary Brecka\'s smoothies use the Elevate brand as their liquid base.' },
    { id: 'earl-grey', name: 'Earl Grey tea', cat: 'brew', band: 'everyday', icon: 'mate', re: /earl grey/,
      blurb: 'Black tea scented with bergamot, cold brewed here for a citrusy, perfumed base. It supplied the bergamot note in DedCool\'s fragrance-inspired Xtra Milk smoothie.' },
    { id: 'coffee-beans', name: 'Coffee beans', cat: 'brew', band: 'everyday', icon: 'coffeeBeans', re: /coffee beans/,
      blurb: 'Whole roasted coffee beans blended for concentrated coffee flavor and texture.' },
    { id: 'herbal-coffee', name: 'Herbal coffee blend', cat: 'brew', band: 'functional', icon: 'coffee', re: /^(?:organic )?(?:dandy blend|(?:[a-z]+ )?herbal coffee(?: blend)?)$/,
      blurb: 'A roasted plant blend prepared as a coffee alternative. The archive lists Dandy Blend. It stays separate from brewed coffee.' },
    { id: 'coffee', name: 'Brewed coffee', cat: 'brew', band: 'everyday', icon: 'coffee', re: /cold brew|espresso|coffee/,
      blurb: 'Coffee prepared as cold brew or espresso and used as a liquid base.' },
    { id: 'matcha', name: 'Matcha', cat: 'brew', band: 'everyday', icon: 'matcha', re: /^(?!.*kiwi).*matcha/,
      blurb: 'Green tea leaves stone ground into a fine powder, so you drink the whole leaf instead of steeping and tossing it. That means more caffeine than brewed green tea, around 60 to 70mg, alongside L-theanine, the amino acid behind matcha\'s steadier lift. Erewhon usually uses Rishi, and it drives the Matchacado, the Kefir Matcha Cloud and Lori Harvey\'s Vanilla Matcha.' },
    { id: 'green-tea', name: 'Green tea', cat: 'brew', band: 'everyday', icon: 'matcha', re: /green tea/,
      blurb: 'Brewed green tea, light and grassy, with modest caffeine and the catechin antioxidants green tea is known for. Erewhon used a citrus version as a base in one 2025 house blend.' },
    { id: 'jasmine-tea', name: 'Jasmine tea', cat: 'brew', band: 'everyday', icon: 'jasmine', re: /jasmine/,
      blurb: 'Green tea scented with jasmine blossoms, delicate and floral with the same gentle caffeine as green tea. It is the clarified base steeped into the Sacred Water tonic rather than blended.' },
    { id: 'hojicha', name: 'Hojicha', cat: 'brew', band: 'everyday', icon: 'hojicha', re: /hojicha/,
      blurb: 'Japanese green tea roasted over charcoal until it turns reddish brown, which burns off most of the caffeine and leaves a toasty, nutty flavor. It carries the Iced Chocolate Hojicha on the tea and matcha menu.' },
    { id: 'hibiscus', name: 'Hibiscus tea', cat: 'brew', band: 'functional', icon: 'hibiscus', re: /hibiscus/,
      blurb: 'A tart, deep red tea brewed from hibiscus flowers, caffeine free. Some studies tie it to small drops in blood pressure. Here it works as a fruit forward base with a cranberry like sourness.' },
    { id: 'rose-water', name: 'Rose water', cat: 'brew', band: 'functional', icon: 'rose', re: /\brose\b|rosewater/,
      blurb: 'Water distilled with rose petals, perfumed and faintly sweet, used where a blend wants to taste like a flower shop smells. It carries the Pasadena store\'s Rose Pasadena, a nod to the City of Roses.' },
    { id: 'chamomile', name: 'Chamomile', cat: 'brew', band: 'functional', icon: 'chamomile', re: /chamomile/,
      blurb: 'The daisy-like flower brewed for the most familiar calming tea. Cold it reads soft and faintly apple-ish, the mellow base under Rho\'s NAD+ & Creatine Dream.' },
    { id: 'butterfly-pea', name: 'Butterfly pea flower', cat: 'brew', band: 'functional', icon: 'butterflypea', re: /butterfly pea/,
      blurb: 'A flower tea that turns liquid vivid blue, then purple when something acidic hits it. It brings the color with almost no flavor, used where a blend needs to look blue.' },
    { id: 'lavender', name: 'Lavender water', cat: 'brew', band: 'functional', icon: 'lavender', re: /lavender/,
      blurb: 'Culinary lavender steeped into water for its floral aroma, long associated with calm. A little goes a long way, so it is used in small amounts for scent more than taste.' },
    { id: 'kombucha', name: 'Kombucha', cat: 'cultured', band: 'functional', icon: 'bottle', re: /kombucha/,
      blurb: 'A fermented tea drink. The archive includes Health-Ade Pomegranate and Synergy Peach Paradise kombucha. GT\'s ALIVE Cola appears under Cola.' },
    { id: 'yerba-mate', name: 'Yerba mate', cat: 'brew', band: 'functional', icon: 'mate', re: /yerba|(?:^|\s)mate\b/,
      blurb: 'A drink made from yerba mate leaves, including the flavored Yerba Madre Bluephoria listing. The source product and flavor remain visible.' },
    { id: 'energy-drink', name: 'Energy drink', cat: 'brew', band: 'functional', icon: 'can', re: /^(?!.*(?:powder|drink mix)).*(?:gorgie|\benergy drink\b)/,
      blurb: 'A prepared caffeinated drink. The archive includes GORGIE Tropical Punch and Cherry Lime, with each product and flavor preserved in the recipes.' },
    { id: 'nonalcoholic-aperitif', name: 'Nonalcoholic aperitif', cat: 'brew', band: 'functional', icon: 'bottle', re: /de soi|kin high rhode|high rhode|non[- ]?alcoholic ap[eé]ritif/,
      blurb: 'A nonalcoholic aperitif used as a prepared smoothie ingredient. The archive includes De Soi Spritz Italiano and Kin High Rhode. Their distinct products and flavors remain visible below.' },
    { id: 'aloe-juice', name: 'Aloe vera juice', cat: 'liquid', band: 'functional', icon: 'aloeJuice', re: /aloe vera.*juice/,
      blurb: 'An aloe drink listed as juice. Kept separate from recipes that only name aloe vera without specifying its form.' },
    { id: 'aloe', name: 'Aloe vera', cat: 'veg', band: 'functional', icon: 'aloe', re: /aloe/,
      blurb: 'Aloe vera listed without a specific preparation. The original label is preserved rather than assuming it means juice or gel.' },
    { id: 'lemonade', name: 'Lemonade', cat: 'brew', band: 'everyday', icon: 'lemonade', re: /^(?:organic )?lemonade$/,
      blurb: 'A prepared lemon drink, listed separately from lemon fruit and straight lemon juice.' },
    { id: 'orange-juice', name: 'Orange juice', cat: 'liquid', band: 'everyday', icon: 'orangeJuice', re: /orange juice|fresh-pressed orange/,
      blurb: 'Fresh squeezed orange juice, sweet and high in vitamin C. It is the citrus base of the Malibu Mango and several glow themed blends, sometimes Evolution Fresh rather than house pressed.' },
    { id: 'juice-blend', name: 'Fruit juice blend', cat: 'liquid', band: 'everyday', icon: 'juiceBlend', re: /orange grapefruit juice|kiwi matcha juice|\bfruit juice blend\b/,
      blurb: 'A bottled or pressed juice made from more than one named ingredient. The combined source wording stays intact rather than being reduced to one fruit.' },
    { id: 'banana-water', name: 'Banana water', cat: 'liquid', band: 'everyday', icon: 'bananaWater', re: /banagua.*banana water|banana water/,
      blurb: 'A packaged banana based drink used as a liquid smoothie base. It is distinct from whole banana, which supplies much more body.' },
    { id: 'apple-juice', name: 'Apple juice', cat: 'liquid', band: 'everyday', icon: 'appleJuice', re: /apple juice/,
      blurb: 'Pressed apple juice used as a sweet liquid base. Unlike whole apple, it contributes little texture to the blend.' },
    { id: 'blueberry-juice', name: 'Blueberry juice', cat: 'liquid', band: 'everyday', icon: 'blueberryJuice', re: /blueberry juice/,
      blurb: 'Pressed blueberry juice, which supplies berry flavor and color without the texture of whole berries.' },
    { id: 'cherry-juice', name: 'Tart cherry juice', cat: 'liquid', band: 'everyday', icon: 'cherryJuice', re: /tart cherry juice/,
      blurb: 'Juice pressed from tart cherries. It is sharper and more liquid than the whole sweet cherries elsewhere in the archive.' },
    { id: 'lemon-juice', name: 'Lemon juice', cat: 'liquid', band: 'everyday', icon: 'lemonJuice', re: /lemon juice/,
      blurb: 'Pressed lemon juice used to add acidity and keep fruit flavors bright.' },
    { id: 'lime-juice', name: 'Lime juice', cat: 'liquid', band: 'everyday', icon: 'limeJuice', re: /lime juice/,
      blurb: 'Pressed lime juice used for a sharp, floral acidity in tropical blends.' },
    { id: 'pomegranate-juice', name: 'Pomegranate juice', cat: 'liquid', band: 'everyday', icon: 'pomegranateJuice', re: /pomegranate juice/,
      blurb: 'Pressed pomegranate juice, tart and deep red, used as a liquid base or accent.' },
    { id: 'watermelon-juice', name: 'Watermelon juice', cat: 'liquid', band: 'everyday', icon: 'watermelonJuice', re: /watermelon juice/,
      blurb: 'Pressed watermelon, a light and mildly sweet liquid base.' },
    { id: 'grape-juice', name: 'White grape juice', cat: 'liquid', band: 'everyday', icon: 'grapeJuice', re: /white grape juice/,
      blurb: 'Pressed white grapes used as a mild, sweet liquid base.' },
    { id: 'ginger-juice', name: 'Ginger juice', cat: 'liquid', band: 'everyday', icon: 'gingerJuice', re: /ginger juice/,
      blurb: 'Pressed ginger juice used in small amounts for a sharp, warming flavor.' },
    { id: 'turmeric-juice', name: 'Turmeric juice', cat: 'liquid', band: 'functional', icon: 'turmericJuice', re: /turmeric juice/,
      blurb: 'Pressed turmeric root, an earthy liquid with a strong golden color.' },
    { id: 'ice', name: 'Ice', cat: 'liquid', band: 'everyday', icon: 'ice', re: /\bice\b/,
      blurb: 'Plain ice, blended in to chill and thicken. Most Erewhon blends skip it because frozen fruit already does the job, but a few cards list it.' },

    /* ---- supplements (before fruits: many contain fruit words) ---- */
    { id: 'collagen', name: 'Collagen', cat: 'supplement', band: 'functional', icon: 'scoop', re: /^(?!.*(?:plant[- ]based|vegan|collagen[- ]free|no collagen|without collagen|boost(?:er)?|support)).*\bcollagen\b|holi ?\(?mane\)?|glowery/,
      blurb: 'Collagen powders and collagen-containing mixes, including marine collagen and products combined with pearl, greens or electrolytes. Each source product stays named below. Copina\'s botanical collagen booster belongs under Plant-based creamer because it contains no collagen peptides.' },
    { id: 'amino', name: 'Amino acids', cat: 'supplement', band: 'functional', icon: 'scoop', re: /perfect ?amino|bcaa|\bamino(?:s| acids?)?\b/,
      blurb: 'Amino acid supplements, including Perfect Amino and BCAAs. Some products also contain electrolytes. Their full names and flavors stay visible, without counting the contents of a mix as separately listed ingredients.' },
    { id: 'electrolytes', name: 'Electrolytes', cat: 'supplement', band: 'functional', icon: 'salt', re: /ultima replenisher|electrolyte|ionic minerals(?! silica)/,
      blurb: 'Electrolyte powders and mineral drops, including Ultima Replenisher and Eidon. Prepared hydration drinks stay separate. Products sold as amino acid or collagen mixes appear under those ingredient types, with their full labels preserved.' },
    { id: 'silica', name: 'Silica', cat: 'supplement', band: 'functional', icon: 'silica', re: /silica/,
      blurb: 'A trace mineral sold for hair, skin and nails, though the body needs little and a normal diet usually covers it. Erewhon adds it as Eidon drops.' },
    { id: 'magnesium', name: 'Magnesium', cat: 'supplement', band: 'functional', icon: 'salt', re: /magnesium|natural vitality.*\bcalm\b/,
      blurb: 'Magnesium supplements used in a smoothie. The archive includes Natural Vitality CALM and a yuzu citrus version from PYM. Product names and flavors remain in the recipe.' },
    { id: 'hyaluronic-acid', name: 'Hyaluronic acid', cat: 'supplement', band: 'functional', icon: 'serum', re: /hyaluronic/,
      blurb: 'A molecule the body makes to hold water in skin and joints, sold as a supplement for hydration though the evidence for swallowing it is mixed. Early versions of the Strawberry Glaze listed NeoCell hyaluronic acid; the current recipe drops it.' },
    { id: 'multivitamin', name: 'Multivitamin', cat: 'supplement', band: 'functional', icon: 'multivitamin', re: /multivitamin|mary\s*ruth|codeage.*hair vitamins|\bhair vitamins?(?: blend)?\b/,
      blurb: 'Preparations combining multiple vitamins, including MaryRuth liquid products and Codeage Hair Vitamins. Some formulas add other supplements. Their product names and listed forms remain visible in each recipe.' },
    { id: 'fulvic', name: 'Fulvic minerals', cat: 'supplement', band: 'functional', icon: 'fulvic', re: /fulvic/,
      blurb: 'Fulvic minerals listed as drops. The named ION Gut Support formula retains its own profile.' },
    { id: 'novos', name: 'NOVOS Core', cat: 'specialty', band: 'functional', icon: 'capsule', re: /novos/,
      blurb: 'A named supplement formula, listed as NOVOS Core Longevity Formula. Its components are not counted as separately listed smoothie ingredients.' },
    { id: 'nad', name: 'NAD+', cat: 'supplement', band: 'functional', icon: 'capsule', re: /\bnad\b|nicotinamide/,
      blurb: 'A coenzyme every cell uses to turn food into energy, whose levels fall with age. Supplements try to top it back up, though whether swallowed NAD+ actually reaches the cells is unsettled. Liposomal NAD+ headlines the 2026 Rho collab.' },
    { id: 'spiced-sugar', name: 'Spiced sugar topping', cat: 'topping', band: 'treats', icon: 'pumpkinSpice', re: /^gold dust \(keto brown sugar & turmeric\)$|\bspiced sugar(?: topping)?\b/,
      blurb: 'A sweet spice topping. The Golden Hour Glow recipe calls it Gold Dust and explicitly lists keto brown sugar and turmeric. That source wording does not describe edible gold.' },
    { id: 'beauty-drops', name: 'Sakara Beauty Drops', cat: 'specialty', band: 'functional', icon: 'beautydrops', re: /sakara.*beauty (?:water )?drops/,
      blurb: 'A named Sakara product listed in the archive. The recipe does not identify its full formula, so this profile preserves the product name.' },
    { id: 'charcoal', name: 'Activated charcoal', cat: 'supplement', band: 'functional', icon: 'charcoal', re: /charcoal/,
      blurb: 'Food grade activated charcoal, a fine black powder that binds to things in the gut. It turns a blend jet black and is used mostly for that, in the goth leaning specials.' },
    { id: 'nootropic', name: 'Nootropic drink mix', cat: 'supplement', band: 'functional', icon: 'scoop', re: /klar|nootropics? drink mix/,
      blurb: 'A powdered drink mix marketed as nootropic. The archive includes KLAR Blood Orange. The term describes its marketing, not a verified effect.' },
    { id: 'magic-mind', name: 'Magic Mind', cat: 'specialty', band: 'functional', icon: 'bottle', re: /magic mind/,
      blurb: 'A named bottled product listed as Magic Mind Mental Performance Shot.' },
    { id: 'reds-powder', name: 'Reds powder', cat: 'super', band: 'functional', icon: 'scoop', re: /bodyhealth reds|\breds powder\b/,
      blurb: 'A blended powder sold as reds. The archive lists BodyHealth Reds. It remains distinct from individual fruit powders.' },
    { id: 'creatine', name: 'Creatine', cat: 'supplement', band: 'functional', icon: 'scoop', re: /creatine/,
      blurb: 'The most studied sports supplement, taken to help muscles refill energy between hard efforts, now crossing into everyday wellness. It arrived with the 2026 wave of performance blends like Wake Up in WeHo.' },
    { id: 'organs', name: 'Beef organ powder', cat: 'supplement', band: 'functional', icon: 'organs', re: /beef organ(?:s| powder)|organs/,
      blurb: 'Freeze dried liver and other organ meats in powder, sold as a concentrated source of vitamin A, B12 and iron. Erewhon used Heart & Soil capsules, Paul Saladino\'s brand, in his raw animal based smoothie.' },
    { id: 'euphoria', name: 'Anima Mundi Euphoria', cat: 'specialty', band: 'functional', icon: 'lavender', re: /anima mundi.*euphoria/,
      blurb: 'A named powder blend from Anima Mundi. Its listed product identity is preserved instead of reducing it to one fruit or herb.' },
    { id: 'pearl', name: 'Pearl powder', cat: 'supplement', band: 'functional', icon: 'pearl', re: /sun potion pearl|\bpearl powder\b/,
      blurb: 'Freshwater pearl ground to powder, a traditional Chinese beauty ingredient taken for skin, mostly calcium and trace minerals. Erewhon used Sun Potion\'s in the skin focused blends.' },

    /* ---- proteins & collagen ---- */
    { id: 'bone-broth-protein', name: 'Bone broth protein', cat: 'supplement', band: 'functional', icon: 'boneBroth', re: /bone broth protein/,
      blurb: 'A powdered protein made from concentrated bone broth. The archive version is vanilla flavored, but it remains distinct from vanilla powder and whey.' },
    { id: 'whey', name: 'A2 whey protein', cat: 'supplement', band: 'functional', icon: 'scoop', re: /whey/,
      blurb: 'A fast digesting milk protein, the gym standard, with the full set of amino acids muscles use to rebuild. Erewhon makes its own, a regenerative organic certified A2 whey, and it is the house protein for the 2025 and 2026 menu.' },
    { id: 'chocho', name: 'Chocho protein', cat: 'supplement', band: 'functional', icon: 'pea', re: /chocho|cho ?cho|mikuna/,
      blurb: 'A plant protein from Andean lupin beans, complete in amino acids and naturally creamy. Erewhon used Mikuna\'s, which replaced whey in the Peanut Butter Blast.' },
    { id: 'plant-protein', name: 'Plant protein', cat: 'supplement', band: 'functional', icon: 'scoop', re: /epic protein|sprout living|four sigmatic.*protein|plant[- ](?:based )?(?:vanilla )?protein|vegan protein/,
      blurb: 'Protein made from plants, including vanilla and chocolate blends. The archive includes Sprout Living Epic Protein, Four Sigmatic and generic vegan protein. Brands and flavors share this profile.' },
    { id: 'colostrum', name: 'Colostrum', cat: 'supplement', band: 'functional', icon: 'scoop', re: /colostrum|immunomilk/,
      blurb: 'Colostrum used as a powdered supplement. The archive includes ARMRA, Cowboy and Heart and Soil Immunomilk. Brands and flavors share one profile.' },

    /* ---- superfoods & adaptogens ---- */
    { id: 'tocos', name: 'Tocos', cat: 'fat', band: 'functional', icon: 'scoop', re: /tocos|tocotrienol|rice bran/,
      blurb: 'Soluble rice bran, a soft vanilla flavored powder rich in vitamin E. It thickens a blend and rounds off the flavor, and it quietly does that in more house smoothies than any other powder.' },
    { id: 'maca', name: 'Maca', cat: 'super', band: 'functional', icon: 'maca', re: /maca\b/,
      blurb: 'A malty Peruvian root powder, an adaptogen tied to energy and hormone balance, though the evidence is early. The house Maca Bomb is built on it.' },
    { id: 'lucuma', name: 'Lucuma', cat: 'fruit', band: 'functional', icon: 'lucuma', re: /lucuma/,
      blurb: 'A Peruvian fruit with a maple-like flavor. It is often sold as powder, but the archive labels only say lucuma, so its preparation is not assumed.' },
    { id: 'mesquite', name: 'Mesquite', cat: 'super', band: 'functional', icon: 'mesquite', re: /mesquite/,
      blurb: 'Ground mesquite pod, smoky sweet and high in fiber, a 1970s health food flavor that survives in the older house recipes.' },
    { id: 'cacao-nibs', name: 'Cacao nibs', cat: 'fat', band: 'everyday', icon: 'cacaoNibs', re: /cacao nibs/,
      blurb: 'Small pieces of crushed cacao bean that add chocolate flavor and a little texture.' },
    { id: 'cacao-powder', name: 'Cacao powder', cat: 'sweet', band: 'everyday', icon: 'cacaoPowder', re: /cacao powder|raw cacao powder/,
      blurb: 'Cacao beans ground into a fine powder that blends evenly into a drink.' },
    { id: 'superfood-chocolate-sauce', name: 'Superfood chocolate sauce', cat: 'topping', band: 'treats', icon: 'chocolateSauce', re: /superfood chocolate sauce/,
      blurb: 'A pourable chocolate preparation used as a topping or swirl.' },
    { id: 'superfood-chocolate', name: 'Superfood chocolate', cat: 'topping', band: 'everyday', icon: 'superfoodChocolate', re: /(?:erewhon )?superfood chocolate$/,
      blurb: 'A prepared chocolate ingredient listed by the archive without a more specific form.' },
    { id: 'cacao', name: 'Cacao', cat: 'sweet', band: 'everyday', icon: 'cacao', re: /cacao|cocoa|chocolate(?! stevia)/,
      blurb: 'Cacao listed without a more specific form in the source.' },
    { id: 'vanilla-syrup', name: 'Vanilla syrup', cat: 'sweet', band: 'everyday', icon: 'vanillaSyrup', re: /vanilla syrup/,
      blurb: 'A sweet liquid flavored with vanilla, used as both a flavoring and sweetener.' },
    { id: 'vanilla', name: 'Vanilla', cat: 'sweet', band: 'everyday', icon: 'vanilla', re: /^(?!.*stevia).*vanilla/,
      blurb: 'Ground whole vanilla bean, warm and floral, doing more flavor work than its small amount suggests. Erewhon often uses Beyond Good\'s Madagascar powder rather than extract.' },
    { id: 'cardamom', name: 'Green cardamom', cat: 'sweet', band: 'everyday', icon: 'cardamom', re: /cardamom/,
      blurb: 'A warm, aromatic spice from the ginger family, its green pods holding fragrant seeds that read floral and citrusy. Green cardamom seasons the Sacred Water tonic.' },
    { id: 'pumpkin-spice', name: 'Pumpkin spice', cat: 'sweet', band: 'everyday', icon: 'pumpkinSpice', re: /pumpkin spice|holiday spice/,
      blurb: 'A warm spice blend used for pumpkin-style flavor. Archive labels do not give a complete spice list.' },
    { id: 'cinnamon', name: 'Cinnamon', cat: 'sweet', band: 'everyday', icon: 'cinnamon', re: /cinnamon/,
      blurb: 'Ground cinnamon, a warm and aromatic spice. The archive includes both generic and Ceylon cinnamon labels.' },
    { id: 'blue-spirulina', name: 'Blue spirulina', cat: 'super', band: 'functional', icon: 'spirulina', re: /blue majik|blue spirulina|luminous spirulina|blue.?green algae/,
      blurb: 'A blue pigment, phycocyanin, pulled out of spirulina algae and sold as an antioxidant. It flavors almost nothing and is mostly there for the color, turning the Coconut Cloud sky blue. Erewhon uses Blue Majik or KOS.' },
    { id: 'spirulina', name: 'Spirulina', cat: 'super', band: 'functional', icon: 'chlorella', re: /spirulina/,
      blurb: 'Whole blue green algae dried to powder, earthy and grassy, dense in protein and iron for its size. The Goddess carries it alongside chlorella and barley grass.' },
    { id: 'chlorella', name: 'Chlorella', cat: 'super', band: 'functional', icon: 'chlorella', re: /chlorella/,
      blurb: 'A freshwater green algae, sold for its chlorophyll and as a binder that may help carry metals out of the body, though that claim is unsettled. Erewhon uses Sun Chlorella, and both Travis Scott\'s and Kacey Musgraves\'s smoothies were partly vehicles for it.' },
    { id: 'chlorophyll', name: 'Chlorophyll', cat: 'super', band: 'functional', icon: 'chlorella', re: /chlorophyll/,
      blurb: 'The green pigment plants use to catch sunlight, taken as a liquid and sold for skin and detox on thin evidence. It made the Poosh Potion glow green.' },
    { id: 'barley-grass', name: 'Barley grass', cat: 'super', band: 'functional', icon: 'grass', re: /barley/,
      blurb: 'The young grass of the barley plant, dried to powder, a green from the original health food era. The Goddess still carries it.' },
    { id: 'greens-powder', name: 'Greens powder', cat: 'super', band: 'functional', icon: 'greenspowder', re: /^(?!.*(?:ready[- ]to[- ]drink|\brtd\b|juice)).*(?:huel daily greens|vitality greens|vibrant greens|greens powder)|^greens$/,
      blurb: 'A prepared greens powder, including Huel Daily Greens and Vitality Greens. Formulas vary by product. They share a browsing profile without counting their components as separate smoothie ingredients.' },
    { id: 'dulse', name: 'Atlantic dulse', cat: 'super', band: 'functional', icon: 'dulse', re: /dulse/,
      blurb: 'A red seaweed eaten dried, salty and savory, prized in the Medical Medium protocol for binding heavy metals. It appears in the Heavy Metal Detox alongside its sibling algae.' },
    { id: 'sea-moss', name: 'Sea moss', cat: 'super', band: 'functional', icon: 'seamoss', re: /sea ?moss/,
      blurb: 'A red seaweed simmered and blended into a gel before it goes in. It thickens a smoothie without dairy and adds a faint ocean note. Once gelled it is mostly water and soluble fiber with trace iodine, which is why it anchors most of the skin and gut themed blends.' },
    { id: 'lions-mane', name: 'Lion\'s mane', cat: 'super', band: 'functional', icon: 'lionsmane', re: /lion.?s mane/,
      blurb: 'A mushroom sold for focus and memory, with early research into its effect on nerve growth. Erewhon uses Om or Host Defense extract, and the Malibu Mango quietly carries it.' },
    { id: 'reishi', name: 'Reishi', cat: 'super', band: 'functional', icon: 'reishi', re: /reishi/,
      blurb: 'A bitter mushroom from Chinese medicine, taken for calm and sleep. Erewhon doses it as Jing Herbs extract.' },
    { id: 'turkey-tail', name: 'Turkey tail', cat: 'super', band: 'functional', icon: 'turkeytail', re: /turkey tail/,
      blurb: 'A mushroom studied mainly for immune support, dense in the same fibers as other medicinal fungi. It appeared in one seasonal special.' },
    { id: 'mushroom-blend', name: 'Chaga', cat: 'super', band: 'functional', icon: 'mushroomblend', re: /chaga/,
      blurb: 'Chaga listed in the archived recipe. Distinct preparations containing multiple ingredients have separate profiles.' },
    { id: 'ashwagandha', name: 'Ashwagandha', cat: 'super', band: 'functional', icon: 'ashwagandha', re: /ashwagandha/,
      blurb: 'The best known adaptogen, a root extract with real research tying it to lower stress and cortisol. It adds no flavor and runs from the Poosh Potion to the Laufey smoothie.' },
    { id: 'astragalus', name: 'Astragalus', cat: 'super', band: 'functional', icon: 'astragalus', re: /astragalus/,
      blurb: 'A root from Chinese medicine taken for immune support, usually as a long term tonic. One of the quieter herbs on the menu.' },
    { id: 'mucuna', name: 'Mucuna', cat: 'super', band: 'functional', icon: 'mucuna', re: /mucuna/,
      blurb: 'A bean extract naturally high in L-dopa, the precursor the body turns into dopamine, sold for mood. One of the more unusual tonics in the archive.' },
    { id: 'cistanche', name: 'Cistanche', cat: 'super', band: 'functional', icon: 'cistanche', re: /cistanche/,
      blurb: 'A desert root from Chinese medicine, taken as an energy and stamina tonic, one of the rarer herbs on the menu.' },
    { id: 'ginkgo', name: 'Ginkgo', cat: 'super', band: 'functional', icon: 'ginkgo', re: /ginkgo/,
      blurb: 'Leaf extract from the ginkgo tree, long sold for memory and circulation, though trials have mostly come up flat. A holdover from an older supplement era.' },
    { id: 'bee-pollen', name: 'Bee pollen', cat: 'super', band: 'functional', icon: 'beepollen', re: /bee pollen/,
      blurb: 'The pollen bees pack into granules, faintly floral and chewy, carrying a little protein and a mix of micronutrients. Erewhon uses Beekeeper\'s Naturals.' },
    { id: 'pine-pollen', name: 'Pine pollen', cat: 'super', band: 'functional', icon: 'beepollen', re: /pine pollen/,
      blurb: 'Pollen from pine trees, a powder from the tonic herb tradition taken as a general vitality booster.' },
    { id: 'saffron', name: 'Saffron', cat: 'sweet', band: 'everyday', icon: 'saffron', re: /saffron(?! latte)/,
      blurb: 'The dried stigmas of the saffron crocus, the most expensive spice there is, lending a honeyed flavor and a golden color from very little. It colored the Golden Hour Glow.' },
    { id: 'camu-camu', name: 'Camu camu', cat: 'fruit', band: 'functional', icon: 'camu', re: /camu/,
      blurb: 'A tart Amazonian fruit. It is often sold as powder, but the archive labels do not specify that preparation.' },
    { id: 'cayenne', name: 'Cayenne', cat: 'sweet', band: 'functional', icon: 'chili', re: /cayenne/,
      blurb: 'Ground cayenne pepper, a pinch of heat used in the detox styled blends for the warming kick its capsaicin gives.' },
    { id: 'turmeric', name: 'Turmeric', cat: 'sweet', band: 'functional', icon: 'turmeric', re: /turmeric/,
      blurb: 'The golden root behind curry color, sold for the anti inflammatory curcumin it contains, though curcumin is hard for the body to absorb without black pepper or fat. Juiced or powdered, it is the base of the house Turmeric Crush.' },
    { id: 'ginger', name: 'Ginger', cat: 'sweet', band: 'everyday', icon: 'ginger', re: /ginger/,
      blurb: 'Fresh ginger, sharp and warming, settling to the stomach and the bite in the immunity leaning blends. Erewhon juices it fresh rather than using powder.' },
    { id: 'mint', name: 'Mint', cat: 'veg', band: 'everyday', icon: 'mint', re: /mint|peppermint/,
      blurb: 'Fresh mint or peppermint, cooling and clean, the lift in the Mint Chip Energizer and Boka\'s smile smoothie.' },
    { id: 'holy-basil', name: 'Holy basil', cat: 'super', band: 'functional', icon: 'holybasil', re: /holy basil|tulsi/,
      blurb: 'Also called tulsi, a basil relative used in Ayurveda as an adaptogen said to help the body handle stress. It brings a clove-like, slightly peppery note to the Sacred Water tonic.' },
    { id: 'anise-hyssop', name: 'Anise hyssop', cat: 'super', band: 'functional', icon: 'anisehyssop', re: /anise hyssop|hyssop/,
      blurb: 'A mint-family herb with tall purple flower spikes and a cool licorice-anise flavor. One of the botanical extracts steeped into the Sacred Water tonic.' },
    { id: 'thyme', name: 'Thyme', cat: 'veg', band: 'everyday', icon: 'thyme', re: /\bthyme\b/,
      blurb: 'A small-leafed culinary herb with an earthy, savory aroma.' },
    { id: 'arugula', name: 'Arugula', cat: 'veg', band: 'everyday', icon: 'arugula', re: /arugula/,
      blurb: 'A peppery leafy green identified explicitly in the source.' },
    { id: 'herbs', name: 'Fresh herbs', cat: 'veg', band: 'everyday', icon: 'spinach', re: /parsley|basil|fresh herbs|cilantro/,
      blurb: 'Fresh parsley, arugula or basil, blended in where a recipe leaned savory and green. They bring a peppery, herbal edge most smoothies skip.' },

    /* ---- fats, nuts, seeds, grains ---- */
    { id: 'almond-butter', name: 'Almond butter', cat: 'fat', band: 'everyday', icon: 'almondbutter', re: /almond butter/,
      blurb: 'Ground roasted almonds, thick and rich, carrying the same good fats and vitamin E as the nuts. It is the richness in the Coconut Cloud and the Almond Butter Blast, doing the work cream would do elsewhere. Erewhon\'s is raw and organic.' },
    { id: 'peanut-butter', name: 'Peanut butter', cat: 'fat', band: 'everyday', icon: 'peanutbutter', re: /peanut butter/,
      blurb: 'Ground peanuts, rich and savory sweet, with protein and good fats. Erewhon uses an organic version as the base of the Peanut Butter Blast.' },
    { id: 'sesame', name: 'Black sesame', cat: 'fat', band: 'everyday', icon: 'sesame', re: /sesame/,
      blurb: 'Black sesame ground to a butter, nutty and a little bitter, high in calcium and good fats. It darkens the OG Goth and deepens the Laufey smoothie.' },
    { id: 'almonds', name: 'Almonds', cat: 'fat', band: 'everyday', icon: 'almond', re: /almonds\b/,
      blurb: 'Whole raw almonds blended straight in, for the same richness as the butter with a little more body. They run through the legacy house recipes.' },
    { id: 'walnuts', name: 'Walnuts', cat: 'fat', band: 'everyday', icon: 'walnut', re: /walnut/,
      blurb: 'Whole walnuts, one of the few plant sources of omega 3 fat, with a soft bitterness. They come from the Function recipe.' },
    { id: 'pistachio', name: 'Pistachio', cat: 'fat', band: 'everyday', icon: 'pistachio', re: /pistachio/,
      blurb: 'A mild green nut with a lightly sweet flavor, blended for richness and texture.' },
    { id: 'chia', name: 'Chia seeds', cat: 'fat', band: 'everyday', icon: 'chia', re: /chia/,
      blurb: 'Tiny seeds that swell into a gel as they soak, thickening a blend and adding fiber and omega 3 fat. A spoonful does a lot.' },
    { id: 'hemp', name: 'Hemp seeds', cat: 'fat', band: 'everyday', icon: 'hemp', re: /hemp/,
      blurb: 'Soft, nutty hemp seeds, a complete plant protein with a good fat balance. A constant in the older house recipes.' },
    { id: 'flax-oil', name: 'Flaxseed oil', cat: 'fat', band: 'everyday', icon: 'oil', re: /flax(?:seed| seed)? oil/,
      blurb: 'Oil pressed from flaxseed. The archive lists Barlean\'s flax oil. It stays separate from the whole seed, which adds a different texture.' },
    { id: 'flax', name: 'Flaxseed', cat: 'fat', band: 'everyday', icon: 'flax', re: /flax/,
      blurb: 'Flaxseed used as a seed ingredient. Flaxseed oil has its own profile.' },
    { id: 'olive-oil', name: 'Olive oil', cat: 'fat', band: 'everyday', icon: 'oliveoil', re: /olive/,
      blurb: 'Extra virgin olive oil, drizzled rather than blended, for a peppery, savory edge. Salt & Stone\'s Salt & Serve used it over soft serve with flaky salt, sweet-meets-savory.' },
    { id: 'mct-oil', name: 'MCT oil', cat: 'fat', band: 'functional', icon: 'oil', re: /\bmct\b/,
      blurb: 'A concentrated coconut fat the body turns to fuel quickly, sold for steady energy, a holdover from the keto years. Flavorless, it blends in clean.' },
    { id: 'oil-blend', name: 'Oil blend', cat: 'fat', band: 'functional', icon: 'oil', re: /udo'?s? oil|\b(?:plant )?oil blend\b|\b(?:blended )?omega oils?\b/,
      blurb: 'Blended oils, including Udo\'s plant oil blend and a recipe labeled Blended Omega Oils. The generic label does not establish a plant or fish source. Individually identified oils keep their own profiles.' },
    { id: 'ghee', name: 'Ghee', cat: 'fat', band: 'functional', icon: 'ghee', re: /ghee/,
      blurb: 'Butter cooked until the milk solids cook off, leaving pure golden fat that keeps without refrigeration. Erewhon blends it into the coffee based Activated like a bulletproof coffee.' },
    { id: 'pumpkin-seed-oil', name: 'Pumpkin seed oil', cat: 'fat', band: 'functional', icon: 'oil', re: /pumpkin seed/,
      blurb: 'A dark green oil pressed from pumpkin seeds, rich in zinc and good fats, with a toasted, nutty flavor. It appears in The Goddess.' },
    { id: 'oats', name: 'Oats', cat: 'fat', band: 'everyday', icon: 'oats', re: /\boats\b/,
      blurb: 'Rolled oats, soft and mild, with the soluble fiber oats are known for. Erewhon uses a gluten free oat for the cake batter texture in the Barbie smoothie.' },
    { id: 'rice', name: 'Rice', cat: 'fat', band: 'everyday', icon: 'rice', re: /lundberg|^(?:organic |cooked )?rice$/,
      blurb: 'Cooked rice blended in for body and a horchata like creaminess. Erewhon used Lundberg rice in Becky G\'s Swirl-Chata.' },

    /* ---- vegetables ---- */
    { id: 'spinach', name: 'Spinach', cat: 'veg', band: 'everyday', icon: 'spinach', re: /spinach/,
      blurb: 'The mildest leafy green, easy to hide in a blend, carrying iron, folate and vitamin K with almost no flavor. It is behind most of the green blends, including the Poosh Potion.' },
    { id: 'kale', name: 'Kale', cat: 'veg', band: 'everyday', icon: 'kale', re: /kale/,
      blurb: 'A sturdier, more mineral dense green than spinach, with a real vegetal flavor. Used where a recipe wanted the green to taste like something.' },
    { id: 'celery', name: 'Celery', cat: 'veg', band: 'everyday', icon: 'celery', re: /celery/,
      blurb: 'Celery listed without a specific preparation. The source does not identify it as juice.' },
    { id: 'cauliflower-rice', name: 'Cauliflower rice', cat: 'veg', band: 'functional', icon: 'cauliflower', re: /cauliflower/,
      blurb: 'Frozen riced cauliflower, a way to make a smoothie thick without the sugar of a banana, with fiber and almost no flavor. Both Gary Brecka recipes lean on it.' },
    { id: 'carrot-juice', name: 'Carrot juice', cat: 'liquid', band: 'everyday', icon: 'carrotJuice', re: /carrot juice/,
      blurb: 'Pressed carrot juice, naturally sweet and orange, used as a liquid base without the texture of whole carrot.' },
    { id: 'carrot', name: 'Carrot', cat: 'veg', band: 'everyday', icon: 'carrot', re: /\bcarrot\b/,
      blurb: 'Whole carrot blended for sweetness, color, and a little texture.' },
    { id: 'pumpkin', name: 'Pumpkin', cat: 'veg', band: 'everyday', icon: 'pumpkin', re: /pumpkin/,
      blurb: 'Pumpkin used for mild flavor and body. The archive lists plain pumpkin puree, grouped here with pumpkin. Pumpkin spice and seed oil stay separate.' },
    { id: 'beet-juice', name: 'Beet juice', cat: 'liquid', band: 'everyday', icon: 'beetJuice', re: /beet juice/,
      blurb: 'Pressed beet juice, deep red and earthy sweet, used as a liquid ingredient rather than a whole vegetable.' },
    { id: 'beet', name: 'Beet', cat: 'veg', band: 'everyday', icon: 'beet', re: /\bbeet\b/,
      blurb: 'Whole beet, an earthy and sweet root vegetable used for color and body.' },

    /* ---- sweeteners ---- */
    { id: 'maple', name: 'Maple syrup', cat: 'sweet', band: 'everyday', icon: 'maple', re: /maple/,
      blurb: 'Pure maple syrup, the house sweetener, with a little more mineral content than white sugar but sugar all the same. Erewhon uses Crown Maple amber, and Lakanto\'s sugar free version in the Brecka recipes.' },
    { id: 'honey', name: 'Honey', cat: 'sweet', band: 'everyday', icon: 'honey', re: /honey|manuka/,
      blurb: 'Honey and honey-based sweeteners, including raw honey, manuka and B. Powered Superfood Honey. B. Powered adds other bee ingredients. Its full product name remains in the recipe, without counting those components separately.' },
    { id: 'stevia', name: 'Stevia', cat: 'sweet', band: 'functional', icon: 'stevia', re: /stevia/,
      blurb: 'A zero calorie sweetener from the stevia leaf, hundreds of times sweeter than sugar with a slight licorice edge. Erewhon uses flavored drops, the legacy menu\'s sugar free sweetener.' },
    { id: 'xylitol', name: 'Xylitol', cat: 'sweet', band: 'functional', icon: 'xylitol', re: /xylitol/,
      blurb: 'A sugar alcohol from birch that sweetens like sugar with fewer calories and no spike in blood sugar. It sweetens the oldest house recipes.' },
    { id: 'sea-salt', name: 'Sea salt', cat: 'sweet', band: 'everyday', icon: 'salt', re: /\bsalt\b/,
      blurb: 'A pinch of salt, which makes blended fruit taste more like itself by lifting the sweetness. It turns up in nine smoothies and counting.' },
    { id: 'balsamic-vinegar', name: 'Balsamic vinegar', cat: 'sweet', band: 'everyday', icon: 'balsamic', re: /balsamic vinegar/,
      blurb: 'A dark, sweet-tart vinegar made from cooked grape must, used in a small amount to sharpen fruit flavors.' },

    /* ---- fruits last ---- */
    { id: 'banana', name: 'Banana', cat: 'fruit', band: 'everyday', icon: 'banana', re: /banana(?! water)/,
      blurb: 'The most used ingredient in the archive. GROW Bananics organic bananas give the blends their body and most of their sweetness, which is why so many recipes need no other sweetener. One ripe banana runs about 400mg of potassium and a few grams of fiber, and the riper it gets the more of its starch turns to sugar.' },
    { id: 'strawberry', name: 'Strawberry', cat: 'fruit', band: 'everyday', icon: 'strawberry', re: /strawberr/,
      blurb: 'Strawberries used fresh, frozen, or freeze-dried. These share one fruit profile, with the listed preparation preserved in each recipe. Juice, glaze, and flavored toppings stay separate.' },
    { id: 'blueberry-powder', name: 'Blueberry powder', cat: 'super', band: 'everyday', icon: 'blueberryPowder', re: /blueberry powder/,
      blurb: 'Blueberries dried and ground into a concentrated fruit powder.' },
    { id: 'blueberry', name: 'Blueberry', cat: 'fruit', band: 'everyday', icon: 'blueberry', re: /blueberr|fruitist/,
      blurb: 'Small dark berries, among the higher fruits in antioxidants, used regular and wild. Wild blueberries, smaller and more intense, carry the Heavy Metal Detox.' },
    { id: 'raspberry', name: 'Raspberry', cat: 'fruit', band: 'everyday', icon: 'raspberry', re: /raspberr/,
      blurb: 'Tart red berries, high in fiber for their size, that brighten the pink and red blends.' },
    { id: 'blackberry', name: 'Blackberry', cat: 'fruit', band: 'everyday', icon: 'blackberry', re: /blackberr/,
      blurb: 'A deep purple berry, dark and a little tart, in the Laufey smoothie and the goth leaning specials.' },
    { id: 'cherry', name: 'Cherry', cat: 'fruit', band: 'everyday', icon: 'cherry', re: /cherry|cherries/,
      blurb: 'Dark sweet cherries, used fresh, dried and as tart cherry juice, the last of which is tied to sleep and recovery. Sofia Richie Grainge\'s Sweet Cherry made it a headline fruit.' },
    { id: 'mango', name: 'Mango', cat: 'fruit', band: 'everyday', icon: 'mango', re: /mango/,
      blurb: 'Sweet tropical fruit, soft and high in vitamin C and A, that purees into a silky base. It anchors the Malibu Mango and the glow themed blends.' },
    { id: 'pineapple', name: 'Pineapple', cat: 'fruit', band: 'everyday', icon: 'pineapple', re: /pineapple|tropical/,
      blurb: 'Bright, sweet tart tropical fruit carrying bromelain, an enzyme that breaks down protein. Usually frozen Woodstock chunks, it lifts the tropical blends.' },
    { id: 'watermelon', name: 'Watermelon', cat: 'fruit', band: 'everyday', icon: 'watermelon', re: /watermelon/,
      blurb: 'Ninety percent water, sweet and pale red, pressed here into juice. It brings natural electrolytes and a little citrulline, which is why it anchors the summery Liquidsteel hydration blend.' },
    { id: 'grape', name: 'Grape', cat: 'fruit', band: 'everyday', icon: 'grape', re: /grape(?!fruit)/,
      blurb: 'Grapes listed without a specific preparation. White grape juice has its own profile.' },
    { id: 'peach', name: 'Peach', cat: 'fruit', band: 'everyday', icon: 'peach', re: /peach|nectarine/,
      blurb: 'Soft, fragrant summer stone fruit, the fruit of Kendall Jenner\'s Peaches & Cream and a few seasonal specials.' },
    { id: 'fig', name: 'Fig', cat: 'fruit', band: 'everyday', icon: 'fig', re: /\bfigs?\b/,
      blurb: 'A soft, sweet fruit filled with tiny seeds. Black Mission figs have dark skin and a rich fruit flavor.' },
    { id: 'apple', name: 'Apple', cat: 'fruit', band: 'everyday', icon: 'apple', re: /\bapple\b/,
      blurb: 'Whole apple, sweet-tart and crisp, used to add fruit flavor and texture.' },
    { id: 'avocado', name: 'Avocado', cat: 'fruit', band: 'everyday', icon: 'avocado', re: /avocado/,
      blurb: 'A fruit that is mostly good fat, adding silk and body with no flavor of its own. It is what makes the skin smoothies feel like mousse.' },
    { id: 'dates', name: 'Dates', cat: 'fruit', band: 'everyday', icon: 'date', re: /\bdates?\b|joolies|meladuco/,
      blurb: 'Whole dried dates, caramel sweet, with the fiber and minerals still in the fruit, which is why Erewhon sweetens with them before anything else. It uses Medjool and Joolies.' },
    { id: 'pitaya-powder', name: 'Pitaya powder', cat: 'super', band: 'everyday', icon: 'pitayaPowder', re: /(?:pitaya|dragon ?fruit) powder/,
      blurb: 'Dragon fruit dried and ground into a vivid magenta powder used for color and fruit flavor.' },
    { id: 'pitaya', name: 'Pitaya', cat: 'fruit', band: 'everyday', icon: 'dragonfruit', re: /pitaya|dragon ?fruit/,
      blurb: 'Whole dragon fruit, a mild fruit with soft flesh and tiny seeds.' },
    { id: 'lemon', name: 'Lemon', cat: 'fruit', band: 'everyday', icon: 'lemon', re: /lemon/,
      blurb: 'Lemon listed without a specific preparation. Labels that explicitly say lemon juice have a separate profile.' },
    { id: 'grapefruit', name: 'Grapefruit', cat: 'fruit', band: 'everyday', icon: 'orange', re: /grapefruit/,
      blurb: 'Tart, slightly bitter citrus, brighter than orange. It cuts through the coconut in the Green Collagen Elixir.' },
    { id: 'lime', name: 'Lime', cat: 'fruit', band: 'everyday', icon: 'lime', re: /\blime\b/,
      blurb: 'Lime listed without a specific preparation. Labels that explicitly say lime juice have a separate profile.' },
    { id: 'goji', name: 'Goji berries', cat: 'fruit', band: 'functional', icon: 'goji', re: /goji/,
      blurb: 'Chewy red berries from the tonic herb tradition, dried and a little sour sweet, carrying antioxidants and a long history in Chinese medicine. They turn up in the Raw Farms smoothie and the Barbie blend.' },
    { id: 'acai', name: 'Açaí', cat: 'fruit', band: 'everyday', icon: 'acai', re: /a[çc]a[íi]/,
      blurb: 'An Amazonian palm berry, deep purple, tart and low in sugar, high in the antioxidants that give its color. Erewhon blends it from Sambazon packs in Miranda Kerr\'s KORA Glow.' },
    { id: 'passionfruit', name: 'Passionfruit', cat: 'fruit', band: 'everyday', icon: 'passionfruit', re: /passion ?fruit|maracuy/,
      blurb: 'Maracuyá pulp, intensely tart and floral, the sharp tropical note in J Balvin\'s Chimba de Smoothie.' },
    { id: 'pomegranate', name: 'Pomegranate', cat: 'fruit', band: 'everyday', icon: 'pomegranate', re: /pomegranate/,
      blurb: 'Pomegranate listed without a specific preparation. Pomegranate juice and flavored kombucha have separate profiles.' },
    { id: 'cranberry', name: 'Cranberry', cat: 'fruit', band: 'everyday', icon: 'goji', re: /cranberr/,
      blurb: 'Sharp, tart red berries tied to urinary health, from the Function recipe.' },
    { id: 'elderberry-syrup', name: 'Elderberry syrup', cat: 'sweet', band: 'functional', icon: 'elderberrySyrup', re: /elderberry syrup/,
      blurb: 'A concentrated elderberry syrup. The Giselderberry Boost lists a bottled Gaia Herbs preparation, separate from its elderberry glaze.' },
    { id: 'elderberry', name: 'Elderberry', cat: 'fruit', band: 'functional', icon: 'elderberry', re: /elderberr/,
      blurb: 'Elderberry listed without a specific preparation. Syrup and glaze have separate profiles when the source names them.' },
    { id: 'sea-buckthorn', name: 'Sea buckthorn', cat: 'fruit', band: 'functional', icon: 'seaBuckthorn', re: /buckthorn/,
      blurb: 'Tart orange berries, listed here as SIBU sea buckthorn puree. The plain puree shares the fruit profile, with its preparation preserved in the recipe.' },
    { id: 'kiwi', name: 'Kiwi', cat: 'fruit', band: 'everyday', icon: 'kiwi', re: /kiwi/,
      blurb: 'Kiwi listed without a specific preparation. Juice blends and glazes have separate profiles.' },
    { id: 'coconut-flakes', name: 'Coconut flakes', cat: 'fruit', band: 'everyday', icon: 'coconutflakes', re: /coconut flakes/,
      blurb: 'Flakes of dried coconut, toasted or raw, mostly there for texture on top.' },
    { id: 'coconut-bacon', name: 'Coconut bacon', cat: 'topping', band: 'everyday', icon: 'coconutBacon', re: /coconut bacon/,
      blurb: 'Thin coconut pieces seasoned and crisped as a savory topping. It stays separate from plain coconut meat and flakes.' },
    { id: 'coconut-meat', name: 'Coconut meat', cat: 'fruit', band: 'everyday', icon: 'coconutMeat', re: /coconut meat|^coconut$/,
      blurb: 'The soft flesh of a young coconut, blended for body and a mild sweetness in the tropical recipes.' },
    { id: 'pink-peppercorn', name: 'Pink peppercorn', cat: 'sweet', band: 'functional', icon: 'peppercorn', re: /peppercorn/,
      blurb: 'Not a true pepper but a dried berry, floral and barely spicy. Laufey\'s Madwoman smoothie used it as its signature twist.' },
    { id: 'cordyceps', name: 'Cordyceps', cat: 'super', band: 'functional', icon: 'mushroom', re: /cordyceps/,
      blurb: 'A powdered fungus ingredient included in some functional blends. The archive source does not state an amount or a specific claimed effect.' },

  ];


  const BY_ID = new Map(CANON.map((c) => [c.id, c]));
  // Keep links to profiles that were consolidated into their base ingredient.
  const ALIASES = {
    'freeze-dried-strawberry': 'strawberry',
    'pumpkin-puree': 'pumpkin',
    'sea-buckthorn-puree': 'sea-buckthorn',
    'natural-vitality-calm': 'magnesium',
    'ultima-replenisher': 'electrolytes',
    'perfect-amino': 'amino',
    'epic-protein': 'plant-protein',
    'huel-greens': 'greens-powder',
    'immunomilk': 'colostrum',
    'yerba-madre-bluephoria': 'yerba-mate',
    'barcode': 'hydration-drink',
    'gt-alive': 'cola',
    'bio-k': 'probiotic-drink',
    'perfect-amino-electrolytes': 'amino',
    'amino-electrolyte-blend': 'amino',
    'jshealth-greens-collagen': 'collagen',
    'greens-collagen-blend': 'collagen',
    'thorne-collagen-plus': 'collagen',
    'ancient-nutrition-hydrate': 'collagen',
    'collagen-blend': 'collagen',
    'marine-collagen': 'collagen',
    'collagen-pearl-blend': 'collagen',
    'copina-collagen-boost': 'plant-creamer',
    'plant-collagen-booster': 'plant-creamer',
    'ultimate-omega': 'fish-oil',
    'b-powered': 'honey',
    'honey-blend': 'honey',
    'holi-mane': 'collagen',
    'copina-sea-moss-refresher': 'sea-moss-drink',
    'blume-pumpkin-spice': 'latte-mix',
    'pumpkin-spice-latte': 'latte-mix',
    'saffron-latte': 'latte-mix',
    'de-soi': 'nonalcoholic-aperitif',
    'kin': 'nonalcoholic-aperitif',
    'dandy-blend': 'herbal-coffee',
    'udos-oil': 'oil-blend',
    'plant-oil-blend': 'oil-blend',
    'omega-oils': 'oil-blend',
    'hair-vitamins': 'multivitamin',
    'gold-dust': 'spiced-sugar',
  };

  // Regexes propose a profile for unfamiliar wording. They never approve it.
  function suggestCanon(raw) {
    const s = String(raw).toLowerCase();
    for (const c of CANON) if (c.re.test(s)) return c.id;
    return null;
  }

  function normalizeRaw(raw) {
    return String(raw).normalize('NFKC').trim().replace(/\s+/g, ' ').toLowerCase();
  }

  const REVIEWED = window.REVIEWED_INGREDIENTS;
  if (!REVIEWED || typeof REVIEWED !== 'object' || Array.isArray(REVIEWED)) {
    throw new Error('Reviewed ingredient labels are missing. Load data/ingredient-labels.js first.');
  }
  const reviewed = new Map(Object.entries(REVIEWED));
  for (const [label, id] of reviewed) {
    if (label !== normalizeRaw(label) || !BY_ID.has(id)) throw new Error(`Invalid reviewed ingredient mapping: ${label}`);
  }
  for (const entry of CANON) {
    const label = normalizeRaw(entry.name);
    if (reviewed.has(label) && reviewed.get(label) !== entry.id) throw new Error(`Conflicting ingredient name: ${label}`);
    reviewed.set(label, entry.id);
  }

  function matchCanon(raw) {
    const label = normalizeRaw(raw);
    return reviewed.get(label) || reviewed.get(label.replace(/^organic\s+/, '')) || null;
  }

  function groupIngredients(rawList) {
    const groups = [];
    const byKey = new Map();
    for (const raw of rawList || []) {
      const id = matchCanon(raw);
      const key = id ? `id:${id}` : `raw:${normalizeRaw(raw)}`;
      let group = byKey.get(key);
      if (!group) {
        group = { id, variants: [] };
        byKey.set(key, group);
        groups.push(group);
      }
      if (!group.variants.includes(raw)) group.variants.push(raw);
    }
    return groups;
  }

  window.ArchiveIngredients = { CANON, CATS, BY_ID, ALIASES, matchCanon, suggestCanon, normalizeRaw, groupIngredients };
})();
